# Generated by Django 4.0 on 2021-12-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlineshop',
            name='product',
        ),
        migrations.AddField(
            model_name='onlineshop',
            name='product',
            field=models.ManyToManyField(to='main.Product'),
        ),
    ]
